before:
  hooks:
    - go fmt ./...
    - go vet ./...
    - staticcheck ./...
    - go mod tidy
    - go mod verify
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/djlechuck/fa-updater/cmd.version={{.Version}} -X github.com/djlechuck/fa-updater/cmd.commit={{.Commit}} -X github.com/djlechuck/fa-updater/cmd.date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
