---
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Audit
      run: make audit

    - name: Install dependencies
      run: go get .

    - name: Build
      run: make build/cmd

    - name: Upload Go binaries
      uses: actions/upload-artifact@v3
      with:
        path: bin/
